import React,{useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import './style.css';
function App(){
 const [menu,setMenu]=useState([]),[cart,setCart]=useState({}),[name,setName]=useState(''),[message,setMessage]=useState('');
 useEffect(()=>{fetch('/api/menu').then(r=>{if(!r.ok)throw Error('Menu unavailable');return r.json()}).then(setMenu).catch(e=>setMessage(e.message))},[]);
 const add=id=>setCart(c=>({...c,[id]:(c[id]||0)+1}));
 const total=menu.reduce((sum,item)=>sum+item.price_inr*(cart[item.id]||0),0);
 async function order(e){e.preventDefault();setMessage('');try{
   const items=Object.entries(cart).filter(([,qty])=>qty>0);
   if(!items.length)throw Error('Add an item first.');
   for(const [id,quantity] of items){const r=await fetch('/api/orders',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({customer_name:name,item_id:Number(id),quantity})});if(!r.ok)throw Error((await r.json()).error||'Order failed')}
   setCart({});setName('');setMessage('Order received! This is a demo; no payment or delivery is arranged.');
 }catch(err){setMessage(err.message+' If some items were submitted, check with the restaurant before retrying.')}}
 return <><nav><div className="wrap nav"><a href="#home" className="logo">Spice<span>House</span></a><div><a href="#menu">Menu</a><a href="#order">Order</a><a href="#about">Our story</a></div></div></nav><header id="home"><div className="wrap hero"><div><p className="eyebrow">VEGETARIAN KITCHEN · FRESH EVERY DAY</p><h1>Good food.<br/><em>Great moments.</em></h1><p>Comforting Indian favourites made with care, colour, and plenty of flavour.</p><a className="button" href="#menu">Explore the menu ↗</a></div><div className="hero-art" role="img" aria-label="Illustrated bowl of food"><span>✦</span><div>🍛</div><small>FRESH • WARM • DELICIOUS</small></div></div></header><section className="wrap intro" id="about"><p className="eyebrow">WELCOME TO SPICEHOUSE</p><h2>A little spice, a lot of heart.</h2><p>From crisp starters to rich mains and sweet endings, discover familiar flavours prepared for a satisfying meal.</p></section><section className="menu-section" id="menu"><div className="wrap"><p className="eyebrow">OUR FAVOURITES</p><h2>Something for every craving.</h2><div className="cards">{menu.map(item=><article key={item.id}><span className="category">{item.category}</span><div className="food-icon">{({Starters:'🥗',Mains:'🍲',Desserts:'🍮',Drinks:'🥭'})[item.category]}</div><h3>{item.name}</h3><p>{item.description}</p><div className="card-footer"><strong>₹{item.price_inr}</strong><button onClick={()=>add(item.id)} aria-label={`Add ${item.name}`}>Add +</button></div></article>)}</div></div></section><section className="wrap order-section" id="order"><div><p className="eyebrow">READY TO EAT?</p><h2>Your order</h2><p>Select dishes above, add your name, and submit a practice order.</p></div><form onSubmit={order}><div>{menu.filter(item=>cart[item.id]).map(item=><div className="line" key={item.id}><span>{item.name} × {cart[item.id]}</span><button type="button" className="remove" onClick={()=>setCart(c=>({...c,[item.id]:Math.max(0,c[item.id]-1)}))}>−</button><strong>₹{item.price_inr*cart[item.id]}</strong></div>)}</div><div className="line total"><span>Total</span><strong>₹{total}</strong></div><label htmlFor="customer">Your name</label><input id="customer" maxLength={80} required value={name} onChange={e=>setName(e.target.value)} placeholder="Enter your name"/><button className="submit" disabled={!total}>Place demo order</button>{message&&<p role="status" className="message">{message}</p>}</form></section><footer><div className="wrap">SpiceHouse · A full stack CI/CD learning project · © 2026</div></footer></>;
}
createRoot(document.getElementById('root')).render(<App/>);
